spring:
  profiles:
    active: dev  # Change to 'test' for testing profile, 'prod' for production
  # jdbc:h2:mem:blogdb In-memory database for testing , # jdbc:h2:file:./blogdb  for file-based database
  datasource:
    h2:
      console:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # create-drop for development, update for production

  devtools:
    enabled: true
    restart:
      enabled: true
      exclude:
        - "**/static/**"
        - "**/public/**"
    livereload:
      enabled: true

  config:
    import:
      - optional:classpath:/application-secure.yaml

server:
  port: 8083

logging:
  level:
    root: INFO